# Generated by Django 3.0.9 on 2021-10-23 21:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='messagelogs',
        ),
        migrations.CreateModel(
            name='edit_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('messagelogs', models.TextField(blank=True, null=True)),
                ('old_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist_app.Tasklist')),
            ],
        ),
    ]
