# Generated by Django 3.0.9 on 2021-10-27 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_auto_20211023_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_page',
            name='oldid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='edit_page',
            name='old_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist_app.Tasklist'),
        ),
        migrations.AlterField(
            model_name='edit_page',
            name='updatedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='clientname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
