# Generated by Django 3.0.9 on 2021-10-28 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0006_remove_edit_page_oldid'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_logs', models.CharField(max_length=200, null=True)),
                ('assig_nee', models.CharField(max_length=100, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('work_from', models.TimeField(blank=True, null=True)),
                ('work_till', models.TimeField(blank=True, null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist_app.edit_page')),
            ],
        ),
    ]
