# Generated by Django 3.0.9 on 2021-10-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0008_auto_20211028_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logs',
        ),
    ]
