# Generated by Django 3.0.9 on 2021-11-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0009_delete_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_page',
            name='blob',
            field=models.BinaryField(null=True),
        ),
    ]
