# Generated by Django 3.0.9 on 2021-11-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0011_auto_20211116_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_page',
            name='blob',
            field=models.BinaryField(null=True),
        ),
    ]
