# Generated by Django 3.0.9 on 2021-11-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0012_auto_20211117_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_page',
            name='blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
