# Generated by Django 3.0.9 on 2021-11-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0013_auto_20211118_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_page',
            name='blob',
            field=models.BinaryField(null=True),
        ),
    ]
