# Generated by Django 3.0.9 on 2021-11-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0015_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='uploaded_file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
