# Generated by Django 3.0.9 on 2021-11-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0016_auto_20211118_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='uploaded_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
