# Generated by Django 3.0.9 on 2021-11-19 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0017_auto_20211119_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='d_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist_app.edit_page'),
        ),
    ]
