# Generated by Django 3.0.9 on 2021-11-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0018_uploadfile_d_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit_page',
            name='blob',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='uploaded_file',
            field=models.FileField(upload_to=''),
        ),
    ]
