# Generated by Django 3.0.9 on 2021-11-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0019_auto_20211119_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_page',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='uploadfile',
        ),
    ]
