# Generated by Django 3.0.9 on 2021-11-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0020_auto_20211120_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit_page',
            name='messagelogs',
        ),
        migrations.RemoveField(
            model_name='edit_page',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='edit_page',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='edit_page',
            name='time_to',
        ),
        migrations.RemoveField(
            model_name='edit_page',
            name='updatedate',
        ),
    ]
