# Generated by Django 3.0.9 on 2021-11-23 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0021_auto_20211123_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_page',
            name='messagelogs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edit_page',
            name='old_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist_app.Tasklist'),
        ),
        migrations.AddField(
            model_name='edit_page',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edit_page',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edit_page',
            name='updatedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
