# Generated by Django 3.0.9 on 2021-11-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0022_auto_20211123_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('d_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist_app.Tasklist')),
            ],
        ),
    ]
