# Generated by Django 3.0.9 on 2021-11-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0025_doc_edit_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='file',
        ),
        migrations.AddField(
            model_name='doc',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='des',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='time1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='time2',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
