# Generated by Django 3.0.9 on 2021-11-26 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0026_auto_20211125_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist_app.Tasklist'),
        ),
    ]
