# Generated by Django 3.0.9 on 2021-12-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0027_auto_20211126_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
