# Generated by Django 3.0.9 on 2021-12-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0028_auto_20211204_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='time1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='time2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
