# Generated by Django 3.0.9 on 2021-12-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0029_auto_20211207_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='client',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
