# Generated by Django 3.0.9 on 2021-12-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0030_doc_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_page',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
