# Generated by Django 3.0.9 on 2021-12-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0033_auto_20211217_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
