# Generated by Django 3.0.9 on 2021-12-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0034_auto_20211217_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit_page',
            name='file',
        ),
    ]
