# Generated by Django 3.0.9 on 2021-12-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0035_remove_edit_page_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='files',
        ),
    ]
