# Generated by Django 3.0.9 on 2021-12-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0036_delete_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_page',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
